/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package g.ult;

/**
 *
 * @author ADMIN
 */
public class FormCreateSch extends javax.swing.JFrame {

    /**
     * Creates new form FormCreateSch
     */
    public FormCreateSch() {
        initComponents();
        this.setBounds(180, 30, 1200, 700);
        this.setResizable(false);
        this.setTitle("Menu tạo Thời khóa biểu");
        update_d();
    }

    public void update_d() {
        repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_edit = new javax.swing.ButtonGroup();
        jp_egv = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jp_em = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jp_el = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btgv = new javax.swing.JButton();
        btmn = new javax.swing.JButton();
        btlp = new javax.swing.JButton();
        JPtop = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbgv = new javax.swing.JCheckBox();
        cbmon = new javax.swing.JCheckBox();
        cblop = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jb_ctkb = new javax.swing.JButton();
        JPcenter = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_GV = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        JPbot = new javax.swing.JPanel();

        jp_egv.setMinimumSize(new java.awt.Dimension(600, 176));
        jp_egv.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 60, 80));

        jLabel5.setText("A");
        jp_egv.add(jLabel5);

        jp_em.setMinimumSize(new java.awt.Dimension(600, 96));
        jp_em.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 60, 40));

        jLabel6.setText("B");
        jp_em.add(jLabel6);

        jp_el.setMinimumSize(new java.awt.Dimension(600, 96));
        jp_el.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 40, 40));

        jLabel7.setText("C");
        jp_el.add(jLabel7);

        btgv.setText("Panel Giáo Viên");

        btmn.setText("Panel Môn");

        btlp.setText("Panel Lớp");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new java.awt.GridLayout(3, 0));

        JPtop.setBackground(new java.awt.Color(255, 255, 255));
        JPtop.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 44, 32));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Chỉnh sửa");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel1.setFocusTraversalPolicyProvider(true);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setIconTextGap(8);
        jLabel1.setPreferredSize(new java.awt.Dimension(70, 34));
        jLabel1.setRequestFocusEnabled(false);
        JPtop.add(jLabel1);

        bg_edit.add(cbgv);
        cbgv.setForeground(new java.awt.Color(0, 0, 0));
        cbgv.setText("Giáo viên");
        cbgv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cbgv.setIconTextGap(8);
        cbgv.setMinimumSize(new java.awt.Dimension(90, 45));
        cbgv.setPreferredSize(new java.awt.Dimension(90, 34));
        cbgv.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbgvItemStateChanged(evt);
            }
        });
        JPtop.add(cbgv);

        bg_edit.add(cbmon);
        cbmon.setForeground(new java.awt.Color(0, 0, 0));
        cbmon.setText("Môn");
        cbmon.setIconTextGap(8);
        cbmon.setPreferredSize(new java.awt.Dimension(60, 30));
        cbmon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbmonItemStateChanged(evt);
            }
        });
        JPtop.add(cbmon);

        bg_edit.add(cblop);
        cblop.setForeground(new java.awt.Color(0, 0, 0));
        cblop.setText("Lớp");
        cblop.setIconTextGap(8);
        cblop.setPreferredSize(new java.awt.Dimension(60, 30));
        cblop.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cblopItemStateChanged(evt);
            }
        });
        JPtop.add(cblop);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Cập nhật");
        jButton1.setPreferredSize(new java.awt.Dimension(88, 36));
        JPtop.add(jButton1);

        jb_ctkb.setText("Tạo thời khóa biểu");
        jb_ctkb.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jb_ctkb.setPreferredSize(new java.awt.Dimension(140, 40));
        JPtop.add(jb_ctkb);

        getContentPane().add(JPtop);

        JPcenter.setLayout(new java.awt.GridLayout(1, 3));

        jT_GV.setBackground(new java.awt.Color(204, 204, 204));
        jT_GV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã GV", "Tên", "Môn dạy", "Số tiết / Tuần"
            }
        ));
        jScrollPane1.setViewportView(jT_GV);

        JPcenter.add(jScrollPane1);

        jTable3.setBackground(new java.awt.Color(204, 204, 204));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã môn", "Tên môn", "Khối", "Tiết / Tuần"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        JPcenter.add(jScrollPane3);

        jTable2.setBackground(new java.awt.Color(204, 204, 204));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã lớp", "Tên lớp", "Khối"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        JPcenter.add(jScrollPane2);

        getContentPane().add(JPcenter);

        JPbot.setBackground(new java.awt.Color(153, 153, 153));
        JPbot.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(JPbot);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbgvItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbgvItemStateChanged
        // TODO add your handling code here:
        if (cbgv.isSelected() == true) {
            JPbot.removeAll();
            JPbot.add(btgv);
            this.revalidate();
            this.repaint();
        }
    }//GEN-LAST:event_cbgvItemStateChanged

    private void cbmonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbmonItemStateChanged
        // TODO add your handling code here:
        if (cbmon.isSelected() == true) {
            JPbot.removeAll();
            JPbot.add(btmn);

            this.revalidate();
            this.repaint();

        }
    }//GEN-LAST:event_cbmonItemStateChanged

    private void cblopItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cblopItemStateChanged
        // TODO add your handling code here:
        if (cblop.isSelected() == true) {
            JPbot.removeAll();
            JPbot.add(btlp);

            this.revalidate();
            this.repaint();

        }
    }//GEN-LAST:event_cblopItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCreateSch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCreateSch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCreateSch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCreateSch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCreateSch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPbot;
    private javax.swing.JPanel JPcenter;
    private javax.swing.JPanel JPtop;
    private javax.swing.ButtonGroup bg_edit;
    private javax.swing.JButton btgv;
    private javax.swing.JButton btlp;
    private javax.swing.JButton btmn;
    private javax.swing.JCheckBox cbgv;
    private javax.swing.JCheckBox cblop;
    private javax.swing.JCheckBox cbmon;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jT_GV;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JButton jb_ctkb;
    private javax.swing.JPanel jp_egv;
    private javax.swing.JPanel jp_el;
    private javax.swing.JPanel jp_em;
    // End of variables declaration//GEN-END:variables
}
