/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.QLTaiKhoan;

import BLL.K_TaiKhoanbus;
import DTO.K_TaiKhoanDTO;
import GUI.Model.Content;
import GUI.QLTaiKhoan.K_check_Val;

import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class K_DoiMatKhaugui extends Content {

    /**
     * Creates new form DoiMatKhaugui
     */
    private String user_c = "";

    public K_DoiMatKhaugui(String userc) {
        this.user_c = userc;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        tf_newpass = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        tf_newpass_ag = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        lb_trangthaidoimk = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        bt_doimatkhau_save = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 255, 255)));
        jPanel1.setPreferredSize(new java.awt.Dimension(597, 100));
        jPanel1.setLayout(new java.awt.GridLayout(1, 1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thay đổi mật khẩu");
        jPanel1.add(jLabel1);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setPreferredSize(new java.awt.Dimension(597, 300));
        jPanel2.setLayout(new java.awt.GridLayout(3, 1));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));
        jPanel4.setLayout(new java.awt.GridLayout(2, 1, 0, 18));

        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("- Nhập mật khẩu mới");
        jPanel7.add(jLabel2);

        jPanel4.add(jPanel7);

        jPanel8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        tf_newpass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel8.add(tf_newpass);

        jPanel4.add(jPanel8);

        jPanel2.add(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));
        jPanel5.setLayout(new java.awt.GridLayout(2, 1, 0, 18));

        jPanel9.setLayout(new java.awt.GridLayout(1, 0));

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("- Nhập lại mật khẩu mới");
        jPanel9.add(jLabel3);

        jPanel5.add(jPanel9);

        jPanel10.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel10.setLayout(new java.awt.GridLayout(1, 0));

        tf_newpass_ag.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel10.add(tf_newpass_ag);

        jPanel5.add(jPanel10);

        jPanel2.add(jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new java.awt.GridLayout(2, 1, 0, 18));

        jPanel11.setLayout(new java.awt.GridLayout(1, 0));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("- Trạng thái");
        jPanel11.add(jLabel4);

        jPanel6.add(jPanel11);

        jPanel12.setLayout(new java.awt.GridLayout(1, 0));

        lb_trangthaidoimk.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lb_trangthaidoimk.setForeground(new java.awt.Color(255, 51, 51));
        jPanel12.add(lb_trangthaidoimk);

        jPanel6.add(jPanel12);

        jPanel2.add(jPanel6);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setPreferredSize(new java.awt.Dimension(597, 100));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 30));

        bt_doimatkhau_save.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_doimatkhau_save.setForeground(new java.awt.Color(0, 0, 0));
        bt_doimatkhau_save.setText("Lưu thay đổi");
        bt_doimatkhau_save.setPreferredSize(new java.awt.Dimension(140, 36));
        bt_doimatkhau_save.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                bt_doimatkhau_saveItemStateChanged(evt);
            }
        });
        bt_doimatkhau_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_doimatkhau_saveMouseClicked(evt);
            }
        });
        jPanel3.add(bt_doimatkhau_save);

        add(jPanel3, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_doimatkhau_saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_doimatkhau_saveMouseClicked
        // TODO add your handling code here:
        System.out.println("pass moi|nhap lai pass moi-" + tf_newpass.getText() + "|" + tf_newpass_ag.getText());
        String s1 = tf_newpass.getText().trim();
        tf_newpass.setText(s1);
        String s2 = tf_newpass_ag.getText().trim();
        tf_newpass_ag.setText(s2);

        if (!s1.equals(s2)) {
            JOptionPane tb = new JOptionPane();
            tb.showMessageDialog(this, "Đổi mật khẩu không thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            lb_trangthaidoimk.setText("- Nhập lại mật khẩu không trùng, mời nhập lại");
            tf_newpass_ag.setText("");

        } else if (s1.equals(s2)) {
            boolean check = K_check_Val.is_newPass(s1);
            System.out.println("Gia tri check - " + check);

            if (check == true) {
                lb_trangthaidoimk.setText("- Đổi mật khẩu thành công.");
                tf_newpass.setText("");
                tf_newpass_ag.setText("");  
                K_TaiKhoanbus tks = new K_TaiKhoanbus();
                tks.set(new K_TaiKhoanDTO(user_c, s1, user_c));
                JOptionPane tb = new JOptionPane();
                tb.showMessageDialog(this, "Đổi mật khẩu thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                lb_trangthaidoimk.setText("- Mật khẩu chỉ chứa các kí tự a-z, A-Z, 0-9 và tối thiểu 8 kí tự và tối đa 24 kí tự");
                JOptionPane tb = new JOptionPane();
                tb.showMessageDialog(this, "Mật khẩu mới không hợp lệ.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                tf_newpass.setText("");
                tf_newpass_ag.setText("");
            }
        }
    }//GEN-LAST:event_bt_doimatkhau_saveMouseClicked

    private void bt_doimatkhau_saveItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_bt_doimatkhau_saveItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_doimatkhau_saveItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_doimatkhau_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lb_trangthaidoimk;
    private javax.swing.JTextField tf_newpass;
    private javax.swing.JTextField tf_newpass_ag;
    // End of variables declaration//GEN-END:variables
}
