/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.QLTaiKhoan;

import BLL.K_TaiKhoanbus;
import GUI.Model.Content;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ADMIN
 */
public class K_Panel_QuanLyTaiKhoan extends Content {

    /**
     * Creates new form Panel_QuanLyTaiKhoan
     */
    public K_Panel_QuanLyTaiKhoan() {
        initComponents();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pn_showTB = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        bt_crtaikhoan = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        tf_khoiphuctk_manv = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        bt_khoiphuc_mk = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 255))));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 204), 5));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 80));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lý tài khoản");
        jPanel1.add(jLabel1);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setPreferredSize(new java.awt.Dimension(300, 240));
        jPanel2.setLayout(new java.awt.GridLayout(2, 1));

        jPanel3.setLayout(new java.awt.GridLayout(1, 3));

        jPanel4.setLayout(new java.awt.GridLayout(3, 1));

        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 1, 2, 2, new java.awt.Color(255, 204, 153)));
        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("* Tạo tài khoản mặc định cho nhân viên");
        jPanel7.add(jLabel2);

        jPanel4.add(jPanel7);

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));
        jPanel10.setLayout(new java.awt.GridLayout(1, 0));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("- Tên đăng nhập - mã nhân viên");
        jPanel10.add(jLabel3);

        jPanel4.add(jPanel10);

        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));
        jPanel13.setLayout(new java.awt.GridLayout(1, 0));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("- Mật khẩu - ngày sinh nhân viên ");
        jPanel13.add(jLabel4);

        jPanel4.add(jPanel13);

        jPanel3.add(jPanel4);

        jPanel14.setLayout(new java.awt.GridLayout(3, 1));

        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));
        jPanel15.setLayout(new java.awt.GridLayout(1, 0));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("- Ví dụ nhân viên A có thông tin bên dưới:");
        jPanel15.add(jLabel5);

        jPanel14.add(jPanel15);

        pn_showTB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));
        pn_showTB.setLayout(new java.awt.GridLayout(1, 0));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("- Mã nhân viên : manvabc");
        pn_showTB.add(jLabel6);

        jPanel14.add(pn_showTB);

        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));
        jPanel17.setLayout(new java.awt.GridLayout(1, 0));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("- Ngày sinh:  12/02/1995");
        jPanel17.add(jLabel7);

        jPanel14.add(jPanel17);

        jPanel3.add(jPanel14);

        jPanel18.setLayout(new java.awt.GridLayout(3, 1));

        jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));
        jPanel19.setLayout(new java.awt.GridLayout(1, 0));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("- Tài khoản mặt định cho nhân viên A sẽ là");
        jPanel19.add(jLabel8);

        jPanel18.add(jPanel19);

        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));
        jPanel20.setLayout(new java.awt.GridLayout(1, 0));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("- Tên đăng nhập: manvabc");
        jPanel20.add(jLabel9);

        jPanel18.add(jPanel20);

        jPanel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));
        jPanel21.setLayout(new java.awt.GridLayout(1, 0));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("- Mật khẩu mặc đinh: 12021995 hoặc 02121995");
        jPanel21.add(jLabel10);

        jPanel18.add(jPanel21);

        jPanel3.add(jPanel18);

        jPanel2.add(jPanel3);

        jPanel5.setLayout(new java.awt.GridLayout(2, 1));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 204), 4));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        bt_crtaikhoan.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        bt_crtaikhoan.setText("Thực hiện tạo tài khoản mặc định cho nhân viên");
        bt_crtaikhoan.setPreferredSize(new java.awt.Dimension(344, 38));
        bt_crtaikhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crtaikhoanMouseClicked(evt);
            }
        });
        jPanel6.add(bt_crtaikhoan, new java.awt.GridBagConstraints());

        jPanel5.add(jPanel6);

        jPanel8.setLayout(new java.awt.GridLayout(1, 3));

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel9.setLayout(new java.awt.GridBagLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Khôi phục mật khẩu mặt định cho nhân viên");
        jPanel9.add(jLabel12, new java.awt.GridBagConstraints());

        jPanel8.add(jPanel9);

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel11.setLayout(new java.awt.GridLayout(2, 0));

        jPanel22.setLayout(new java.awt.GridLayout(1, 0));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Nhập mã nhân viên để khôi phục");
        jPanel22.add(jLabel11);

        jPanel11.add(jPanel22);

        jPanel23.setLayout(new java.awt.GridBagLayout());

        tf_khoiphuctk_manv.setMinimumSize(new java.awt.Dimension(182, 22));
        tf_khoiphuctk_manv.setPreferredSize(new java.awt.Dimension(182, 22));
        tf_khoiphuctk_manv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_khoiphuctk_manvMouseClicked(evt);
            }
        });
        jPanel23.add(tf_khoiphuctk_manv, new java.awt.GridBagConstraints());

        jPanel11.add(jPanel23);

        jPanel8.add(jPanel11);

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel12.setLayout(new java.awt.GridBagLayout());

        bt_khoiphuc_mk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bt_khoiphuc_mk.setText("Khôi phục mật khẩu");
        bt_khoiphuc_mk.setPreferredSize(new java.awt.Dimension(166, 36));
        bt_khoiphuc_mk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_khoiphuc_mkMouseClicked(evt);
            }
        });
        jPanel12.add(bt_khoiphuc_mk, new java.awt.GridBagConstraints());

        jPanel8.add(jPanel12);

        jPanel5.add(jPanel8);

        jPanel2.add(jPanel5);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_crtaikhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crtaikhoanMouseClicked
        // TODO add your handling code here:
        K_TaiKhoanbus tkbus = new K_TaiKhoanbus();
        try {
            tkbus.createTK();
        } catch (ParseException ex) {
            Logger.getLogger(K_Panel_QuanLyTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane tb = new JOptionPane();
        tb.showMessageDialog(pn_showTB, "Tạo thành công tài khoản mặc định cho nhân viên", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_bt_crtaikhoanMouseClicked

    private void tf_khoiphuctk_manvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_khoiphuctk_manvMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_tf_khoiphuctk_manvMouseClicked

    private void bt_khoiphuc_mkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_khoiphuc_mkMouseClicked
        // TODO add your handling code here:
//         boolean ch = false;
        K_TaiKhoanbus tkbus = new K_TaiKhoanbus();
//        if (check_Val.is_MANV(tf_khoiphuctk_manv.getText().trim())) {
//
//            ch = tkbus.is_exist(tf_khoiphuctk_manv.getText());
//        }

        if (tkbus.is_exist(tf_khoiphuctk_manv.getText().trim())) {
            try {
                tkbus.reset(tf_khoiphuctk_manv.getText().trim());
            } catch (ParseException ex) {
                Logger.getLogger(K_Panel_QuanLyTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane tb = new JOptionPane();
            System.out.println("MANV: " + tf_khoiphuctk_manv.getText().trim() + " khoi phuc mk thanh cong.");
            tb.showMessageDialog(pn_showTB, "Khôi phục mật khẩu mặc định thành công.", "Mã nhân viên: " + tf_khoiphuctk_manv.getText().trim(), JOptionPane.INFORMATION_MESSAGE);
            tf_khoiphuctk_manv.setText("");
        } else {
            JOptionPane tb = new JOptionPane();
            tb.showMessageDialog(pn_showTB, "Mã nhân viên không tồn tại!", "Khôi phục thất bại.", JOptionPane.INFORMATION_MESSAGE);
            tf_khoiphuctk_manv.setText("");
        }
    }//GEN-LAST:event_bt_khoiphuc_mkMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_crtaikhoan;
    private javax.swing.JButton bt_khoiphuc_mk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel pn_showTB;
    private javax.swing.JTextField tf_khoiphuctk_manv;
    // End of variables declaration//GEN-END:variables
}
